import { motion } from 'framer-motion'
import { FileText, AlertTriangle, CreditCard, Users, Scale, Mail } from 'lucide-react'
import './Legal.css'

function Terms() {
  return (
    <div className="legal-page">
      <div className="legal-hero">
        <div className="container">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="legal-icon">
              <FileText size={32} />
            </div>
            <h1>Terms of Service</h1>
            <p className="legal-updated">Last updated: December 2024</p>
          </motion.div>
        </div>
      </div>

      <div className="container">
        <motion.div 
          className="legal-content"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          <section>
            <h2>Acceptance of Terms</h2>
            <p>By downloading, installing, or using AI Image Detector, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the app.</p>
          </section>

          <section>
            <h2>Description of Service</h2>
            <p>AI Image Detector is a mobile application that analyzes images to estimate the probability that they were generated by artificial intelligence. The app uses various forensic analysis techniques to provide this estimation.</p>
          </section>

          <div className="warning-box">
            <AlertTriangle size={24} />
            <div>
              <h3>Important Disclaimer</h3>
              <p>The analysis provided by AI Image Detector is an <strong>estimation</strong> based on heuristic algorithms. No detection method is 100% accurate. Results should be considered as guidance only, not definitive proof of whether an image is AI-generated. We do not guarantee the accuracy of any analysis results. The app may produce false positives or false negatives.</p>
            </div>
          </div>

          <section>
            <h2>Premium Subscriptions</h2>
            <ul>
              <li>Premium subscriptions remove advertisements from the app</li>
              <li>Subscriptions are billed through your Apple ID account</li>
              <li>Subscriptions auto-renew unless cancelled at least 24 hours before the end of the current period</li>
              <li>You can manage and cancel subscriptions in your device's Settings → Apple ID → Subscriptions</li>
              <li>No refunds will be provided for partial subscription periods</li>
            </ul>
          </section>

          <section>
            <h2>User Conduct</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the app for any illegal or unauthorized purpose</li>
              <li>Attempt to reverse engineer or modify the app</li>
              <li>Use the app to harass, defame, or harm others</li>
              <li>Misrepresent analysis results as definitive proof</li>
              <li>Use automated systems to access the app</li>
            </ul>
          </section>

          <section>
            <h2>Intellectual Property</h2>
            <p>All content, features, and functionality of AI Image Detector, including but not limited to algorithms, design, graphics, and user interface, are owned by us and are protected by international copyright, trademark, and other intellectual property laws.</p>
          </section>

          <section>
            <h2>Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from:</p>
            <ul>
              <li>Your use or inability to use the app</li>
              <li>Any decisions made based on analysis results</li>
              <li>Unauthorized access to your data</li>
              <li>Any third-party conduct or content</li>
            </ul>
          </section>

          <section>
            <h2>Indemnification</h2>
            <p>You agree to indemnify and hold harmless AI Image Detector and its developers from any claims, damages, or expenses arising from your use of the app or violation of these terms.</p>
          </section>

          <section>
            <h2>Termination</h2>
            <p>We reserve the right to terminate or suspend your access to the app at any time, without prior notice or liability, for any reason, including breach of these Terms.</p>
          </section>

          <section>
            <h2>Governing Law</h2>
            <p>These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles.</p>
          </section>

          <section>
            <h2>Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. We will notify users of any material changes by updating the "Last updated" date. Continued use of the app after changes constitutes acceptance of the new terms.</p>
          </section>

          <div className="contact-box">
            <Mail size={24} />
            <div>
              <h3>Contact Us</h3>
              <p>If you have any questions about these Terms of Service, please contact us at:</p>
              <a href="mailto:support@aiimagedetector.app">support@aiimagedetector.app</a>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  )
}

export default Terms
